site_name: odatafy
theme: material
nav:
    - Home: index.md
#    - Getting-Started: getting-started.md
    - Feature-Support: feature-support.md
#    - FAQ: faq.md
markdown_extensions:
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
        options:
            attributes:
                align: middle
                height: 20px
                width: 20px
    


    
