site_name: odatafy
theme: readthedocs
nav:
    - Home: index.md
    - URL Structure: url.md
    - Plugins: plugins.md
    - Feature-Support: feature-support.md
    - FAQ: faq.md
markdown_extensions:
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
        options:
            attributes:
                align: absmiddle
                height: 20px
                width: 20px
            image_path: https://assets-cdn.github.com/images/icons/emoji/unicode/

    
