site_name: odatafy
theme: readthedocs
nav:
    - Home: index.md
    - URL Structure: url.md
    - Plugins: plugins.md
    - Feature-Support: feature-support.md
    - FAQ: faq.md
markdown_extensions:
    - pymdownx:
        emoji_generator: https://cdnjs.cloudflare.com/ajax/libs/emojione/2.2.7/assets/png/64/

    
