name: Generate the docs

on: 
  push: 
    branches:
      - main 


jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:

    # Any prerequisite steps
    - uses: actions/checkout@master

    - name: Install mkdocs
      run: pip install mkdocs
      
    - name: Install Markdown extension
      run: pip install pycmarkgfm
      
    - name: Build mkdocs
      run: mkdocs build

    # Deploy to local repo
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: docs
        FOLDER: site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
